---
platform: linux
image: docker:///concourse/static-golang

inputs:
- name: semver-resource
  path: gopath/src/github.com/scopej/semver-resource

outputs:
- name: built-resource

params:
  SEMVER_TESTING_ACCESS_KEY_ID:
  SEMVER_TESTING_SECRET_ACCESS_KEY:
  SEMVER_TESTING_BUCKET:
  SEMVER_TESTING_REGION:

run:
  path: gopath/src/github.com/scopej/semver-resource/scripts/ci
